#spring:
  #application:
    #name: user-ribbon-client
server:
  port: 8080
##服务提供信息
#provider:
  #service:
    #name: user-service-provider
    #host: localhost
    #port: 9090

##关闭Eureka Client,显示通过配置方式注册Ribbon地址
#eureka:
  #client:
    #enabled: true
    #serviceUrl:
      #defaultZone: http://localhost:10000/eureka

##定义 user-service-provider Ribbon的服务地址
##提供 RibbonLoadBalancerClient提供服务列表

user-service-provider:
  ribbon:
    ## 使用eureka ,注释掉
    ##listOfServers: http://${provider.service.host}:${provider.service.port}

##扩展IPing实现
    NFLoadBalancerPingClassName: com.bxw.ribbon.client.ping.MyPing

## 配置 @FeignClient(name = "${user.service.name}") 中的占位符## user.service.name
## 实际需要制定 UserService 接口的提供方## 也就是 user-service-provider，
## 可以使用 ${provider.service.name} 替代
# user.service.name: ${provider.service.name}


