spring:
  application:
    name: spring-cloud-eureka-client

server:
  port: 8083

management:
  security:
    enabled: false

##配置连接多个Eureka服务器
##配置多个Eureka注册中心，以“,”分割
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka,http://localhost:9091/eureka
      cn: http://localhost:9090/eureka,http://localhost:9091/eureka
    ##调整获取所有应用元信息间隔时间
    registry-fetch-interval-seconds: 5
    ## 调整应用元信息间隔时间
    instance-info-replication-interval-seconds: 5




