##节点1完整配置
server:
  port: 9090

## peer2 主机：localhost  端口：9091
peer2:
  server:
    host: localhost
    port: 9091

## Eureka注册信息
eureka:
  client:
    service-url:
      defaultZone: http://${peer2.server.host}:${peer2.server.port}/eureka

