spring:
  application:
    name: spring-cloud-ribbon-client
server:
  port: 8080
management:
  security:
    enabled: false
eureka:
  client:
    ## 暂时性关闭 Eureka 注册
    ## 当使用 Eureka 服务发现时，请注释掉一下配置
    ## enabled: false
    service-url:
      defaultZone: http://localhost:10000/eureka/
    registry-fetch-interval-seconds: 5


##服务提供方主机
service-provider:
  host: localhost
  port: 9090
  name: spring-cloud-service-provider

##配置ribbon服务提供方
##当使用eureka服务发现时，注释掉
##spring-cloud-service-provider:
  ribbon:
    listOfServers: http://${serivce-provider.host}:${serivce-provider.port}

